import type { User, Jewelry, Booking, Transaction, Review } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@goldlink.com",
    firstName: "Admin",
    lastName: "GoldLink",
    phone: "+212600000001",
    role: "admin",
    verified: true,
    rating: 5,
    reviewCount: 0,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    email: "fatima@example.com",
    firstName: "Fatima",
    lastName: "Zahra",
    phone: "+212600000002",
    role: "seller",
    avatar: "/moroccan-woman.jpg",
    verified: true,
    rating: 4.8,
    reviewCount: 24,
    createdAt: new Date("2024-02-15"),
    address: "Casablanca, Morocco",
  },
  {
    id: "3",
    email: "karim@bijouterie.ma",
    firstName: "Karim",
    lastName: "Bennani",
    phone: "+212600000003",
    role: "jeweler",
    avatar: "/moroccan-jeweler.jpg",
    verified: true,
    rating: 4.9,
    reviewCount: 156,
    createdAt: new Date("2024-01-10"),
    address: "Marrakech, Morocco",
  },
  {
    id: "4",
    email: "amina@example.com",
    firstName: "Amina",
    lastName: "El Fassi",
    phone: "+212600000004",
    role: "buyer",
    avatar: "/elegant-woman.png",
    verified: true,
    rating: 4.7,
    reviewCount: 12,
    createdAt: new Date("2024-03-20"),
    address: "Rabat, Morocco",
  },
]

export const mockJewelry: Jewelry[] = [
  {
    id: "1",
    ownerId: "2",
    title: "Collier Traditionnel Marocain en Or 18K",
    description:
      "Magnifique collier traditionnel marocain en or 18 carats, parfait pour les mariages et cérémonies. Pièce unique avec des motifs berbères authentiques.",
    images: ["/moroccan-gold-necklace.jpg", "/traditional-gold-jewelry.jpg", "/gold-necklace-detail.jpg"],
    type: "necklace",
    weight: 45.5,
    purity: 18,
    dimensions: "45cm de longueur",
    estimatedValue: 85000,
    listingType: ["rent", "sale"],
    rentPricePerDay: 1200,
    salePrice: 85000,
    available: true,
    location: "Casablanca",
    createdAt: new Date("2024-11-01"),
    views: 234,
    rating: 4.9,
    reviewCount: 8,
  },
  {
    id: "2",
    ownerId: "3",
    title: "Bracelet en Or 22K avec Pierres Précieuses",
    description: "Bracelet élégant en or 22 carats orné de pierres précieuses. Idéal pour les occasions spéciales.",
    images: ["/gold-bracelet-with-gems.jpg", "/luxury-gold-bracelet.jpg"],
    type: "bracelet",
    weight: 28.3,
    purity: 22,
    dimensions: "18cm",
    estimatedValue: 52000,
    listingType: ["rent", "sale"],
    rentPricePerDay: 800,
    salePrice: 52000,
    available: true,
    location: "Marrakech",
    createdAt: new Date("2024-11-05"),
    views: 189,
    rating: 4.8,
    reviewCount: 5,
  },
  {
    id: "3",
    ownerId: "3",
    title: "Boucles d'Oreilles en Or 18K",
    description: "Paire de boucles d'oreilles raffinées en or 18 carats avec design moderne.",
    images: ["/gold-earrings-elegant.jpg", "/modern-gold-earrings.jpg"],
    type: "earrings",
    weight: 12.5,
    purity: 18,
    estimatedValue: 18500,
    listingType: ["rent", "sale"],
    rentPricePerDay: 350,
    salePrice: 18500,
    available: true,
    location: "Marrakech",
    createdAt: new Date("2024-11-10"),
    views: 145,
    rating: 4.7,
    reviewCount: 3,
  },
  {
    id: "4",
    ownerId: "2",
    title: "Bague de Fiançailles en Or 24K",
    description: "Bague de fiançailles exceptionnelle en or pur 24 carats avec diamant central.",
    images: ["/gold-engagement-ring-diamond.jpg", "/luxury-gold-ring.jpg"],
    type: "ring",
    weight: 8.2,
    purity: 24,
    dimensions: "Taille 54",
    estimatedValue: 35000,
    listingType: ["sale"],
    salePrice: 35000,
    available: true,
    location: "Casablanca",
    createdAt: new Date("2024-11-12"),
    views: 312,
    rating: 5.0,
    reviewCount: 2,
  },
  {
    id: "5",
    ownerId: "3",
    title: "Chaîne en Or 22K Style Moderne",
    description: "Chaîne en or 22 carats au design contemporain, parfaite pour un usage quotidien ou spécial.",
    images: ["/modern-gold-chain.jpg", "/gold-chain-necklace.jpg"],
    type: "chain",
    weight: 35.0,
    purity: 22,
    dimensions: "50cm",
    estimatedValue: 62000,
    listingType: ["rent", "sale"],
    rentPricePerDay: 950,
    salePrice: 62000,
    available: true,
    location: "Marrakech",
    createdAt: new Date("2024-11-15"),
    views: 98,
    rating: 4.6,
    reviewCount: 4,
  },
  {
    id: "6",
    ownerId: "2",
    title: "Pendentif en Or 18K avec Émeraude",
    description: "Pendentif élégant en or 18 carats serti d'une émeraude naturelle.",
    images: ["/gold-pendant-emerald.jpg", "/luxury-gold-pendant.jpg"],
    type: "pendant",
    weight: 15.8,
    purity: 18,
    estimatedValue: 28000,
    listingType: ["rent"],
    rentPricePerDay: 450,
    available: true,
    location: "Casablanca",
    createdAt: new Date("2024-11-18"),
    views: 167,
    rating: 4.8,
    reviewCount: 6,
  },
]

export const mockBookings: Booking[] = [
  {
    id: "1",
    jewelryId: "1",
    renterId: "4",
    ownerId: "2",
    startDate: new Date("2024-12-15"),
    endDate: new Date("2024-12-17"),
    totalPrice: 3600,
    deposit: 8500,
    status: "confirmed",
    createdAt: new Date("2024-11-20"),
    insurance: true,
  },
]

export const mockTransactions: Transaction[] = [
  {
    id: "1",
    bookingId: "1",
    jewelryId: "1",
    buyerId: "4",
    sellerId: "2",
    amount: 3600,
    commission: 360,
    status: "completed",
    type: "rent",
    createdAt: new Date("2024-11-20"),
  },
]

export const mockReviews: Review[] = [
  {
    id: "1",
    userId: "4",
    targetId: "1",
    targetType: "jewelry",
    rating: 5,
    comment: "Magnifique collier, exactement comme décrit. La transaction s'est très bien passée.",
    createdAt: new Date("2024-11-22"),
  },
  {
    id: "2",
    userId: "4",
    targetId: "2",
    targetType: "user",
    rating: 5,
    comment: "Propriétaire très professionnel et arrangeant. Je recommande vivement!",
    createdAt: new Date("2024-11-22"),
  },
]

// Gold price per gram (mock data - in real app, this would be fetched from an API)
export const GOLD_PRICE_PER_GRAM = {
  18: 450, // MAD per gram for 18K
  22: 550, // MAD per gram for 22K
  24: 600, // MAD per gram for 24K
}
